name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup node 14.15.5
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15.5

            - name: npm install
              run: npm install

            - name: npm run format:check
              run: npm run format:check

            - name: npm run lint
              run: npm run lint

            - name: npm run build:dist
              run: npm run build:dist

            - name: npm test
              run: npm test

    release:
        env:
            NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        name: semantic-release
        runs-on: ubuntu-latest
        needs: [build]
        if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"

            - name: Install semantic-release
              run: npm i -g semantic-release

            - name: Release
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: npx semantic-release
