name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup node 14.15.5
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15.5

            - name: npm install
              run: npm install

            - name: npm run build:dist
              run: npm run build:dist

            - name: npm run lint
              run: npm run lint

            - name: npm test
              run: npm test
