name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup node 18.16.0
              uses: actions/setup-node@v4
              with:
                  node-version: 18.16.0

            - name: npm install
              run: npm ci

            - name: npm run format:check
              run: npm run format:check

            - name: npm run lint
              run: npm run lint

            - name: npm run build:dist
              run: npm run build:dist

            - name: npm test
              run: npm test
