name: deploy-docs

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    deploy-docs:
        runs-on: ubuntu-latest
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup node 14.15.5
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15.5

            - name: npm run deploy-docs
              run: npm run deploy-docs
