name: smoke-test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 1 * * *" # Every day at 01:00 AM

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.15.5

            - run: npm install
            - run: npm install -g yalc
            - run: yalc publish
            - run: yalc add eslint-plugin-collation

            - uses: AriPerkkio/eslint-remote-tester-run-action@v3
              with:
                  issue-title: "Results of scheduled smoke test"
                  eslint-remote-tester-config: eslint-remote-tester.config.js
