name: smoke-test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 1 * * *" # Every day at 01:00 AM

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup node 18.16.0
              uses: actions/setup-node@v4
              with:
                  node-version: 18.16.0

            - run: npm ci
            - run: npm install -g yalc
            - run: npm run build
            - run: yalc publish --no-scripts
            - run: yalc add eslint-plugin-collation

            - uses: AriPerkkio/eslint-remote-tester-run-action@v5
              with:
                  issue-title: "Results of scheduled smoke test"
                  eslint-remote-tester-config: eslint-remote-tester.config.js
